app_image:
    resource: "@AppBundle/Controller/ImageController.php"
    type:     annotation

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
